name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.5"
          enable-cache: true

      - name: Install Python 3.12
        run: uv python install 3.12

      - name: Build distributions
        run: uv build

      - name: Smoke test wheel
        run: uv run --isolated --no-project --with dist/*.whl tests/smoke_test.py

      - name: Smoke test sdist
        run: uv run --isolated --no-project --with dist/*.tar.gz tests/smoke_test.py

      - name: Publish
        run: uv publish
